### PR TITLE
Detached header: fix bootstrap calls and sleeps, remove extra bracket

### PR DESCRIPTION
**Pull request by reagentoo**
defaults/initrd.scripts: openLUKS(): remove extra bracket in conditional block
defaults/initrd.scripts: start_LUKS_*(): fix bootstrap calls and sleeps

### CODE REVIEW

**Comment by reagentoo** [comment]
@maciejsszmigiero, @robbat2, @FlyingWaffleDev make review please.
But can't check it right now, genkernel-9999 doesn't build:
```
# genkernel ramdisk
* Gentoo Linux Genkernel; Version 4.2.6-19-gedefa80-git
* Using genkernel configuration from '/etc/genkernel.conf' ...
* Running with options: ramdisk
* Could not find source file '/usr/share/genkernel/distfiles/keyutils-1.6.3.tar.gz'!
* ERROR: Please add missing source file(s) or re-install genkernel!
```

**Comment by maciejsszmigiero** [comment]
> But can't check it right now, genkernel-9999 doesn't build:
> * Could not find source file '/usr/share/genkernel/distfiles/keyutils-1.6.3.tar.gz'!
> * ERROR: Please add missing source file(s) or re-install genkernel!

As the error message says you need to provide this file until the live genkernel ebuild is updated to provide it automatically.

The easiest way to achive this is probably to execute `emerge -fv --nodeps sys-apps/keyutils` and copy the downloaded file from the Portage distfiles directory (for example `/usr/portage/distfiles/`) to `/usr/share/genkernel/distfiles/`.

**Comment by reagentoo** [comment]
Built, tested.

**Comment by robbat2** [comment]
I did update genkernel-9999 already for the new distfile; but I want some more eyes on this PR first from @maciejsszmigiero and @FlyingWaffleDev

**Comment by FlyingWaffleDev** [comment]
I'll test it when I get home; just looking at the changes though, they look logically sound to me.

**Comment by reagentoo** [comment]
@maciejsszmigiero Perhaps for a complete understanding, you need to view initial state of these sections of code. Before detached headers commit: https://github.com/gentoo/genkernel/commit/73a05632d61171685ac4960c6b684cefa6d82afd#diff-250495cd09b817485de6cdeabc8cc126fac65148db822543ca46faf7e1599f91L2344-L2345

**Comment by maciejsszmigiero** [comment]
I will review this PR in the coming days (most likely during this weekend).

**Comment by FlyingWaffleDev** [comment]
Just tested; works fine for me.

**Comment by maciejsszmigiero** [comment]
Looks good to me.

Seems to work fine, too.

**Comment by robbat2** [comment]
merged; thanks!

**Pull request merged**
