### PR TITLE
Enable threaded ZSTD compression by default

### PR DESCRIPTION
**Pull request by maratik123**
Enabling zstd multithreaded compression gives same boost as enabling it for XZ compression in previous commit

### CODE REVIEW

**Comment by ryao** [comment]
There should actually be a slight decrease in compression since the way the threading works is that it splits things into chunks that are compressed independently. That misses compression opportunities across chunks. That said, as long as the chunk size is sufficiently large, the amount of lost compression opportunities will be small, so the result will only be slightly bigger based on what I have seen in the past when doing experiments when recompressing Linux kernel tarballs. That is a good tradeoff in my opinion.

**Comment by maratik123** [comment]
I mean boost in terms of compression time. Slight drop in compression ratio is negligible, at my point.

**Comment by thesamesam** [comment]
Can you add sign-off to your commit please? thanks!

**Comment by maratik123** [comment]
> Can you add sign-off to your commit please? thanks!

Create new PR #48 with signed-off-by commit. Closing this PR now.

**Pull request closed without merging**
