### PR TITLE
Add support for LUKS detached header (another attempt)

### PR DESCRIPTION
**Pull request by reagentoo**
Not tested yet. Feel free to make review and criticize.

### CODE REVIEW

**Review by Androphin — APPROVED** [review]
Looks like the same code from my earlier pull request with minor additions. I'm already using this and it works nice.

**Comment by Androphin** [comment]
I tested the code from this repo and there is a check missing here https://github.com/gentoo/genkernel/blob/master/defaults/initrd.scripts#L1816
If a device is a LUKS device, the detached header must also be used in the cryptsetup isLuks command. Else the device will always be seen as a non LUKS device.
That's what I did here: https://github.com/Androphin/genkernel/blob/master/defaults/initrd.scripts#L1948 (until line 1978)

**Comment by Androphin** [comment]
This is my changed working initrd.scripts file from this luks_header branch.
[initrd.zip](https://github.com/gentoo/genkernel/files/5541579/initrd.zip)

**Comment by reagentoo** [comment]
@Androphin Hi. Thanks for the advice!
I did everything according to your recommendations. But I still haven't tested due to lack of time. :(
I'll try to test it in holidays.

Regarding the changes themselves:
1. `cryptsetup isLuks` with `--header` option was added
2. Had to sacrifice the paddings that was originally. I've simplified the constructions like:
```
if ...
        case1
        continue
else
        case2
fi
```
To:
```
if ...
        case1
        continue
fi
case2
```
(and I don't understand what is the point of making such constructions with `else` block)

**Comment by reagentoo** [comment]
I've just tested current patches. And now I'm using them to boot my main system.
Now I'm confident it works.

My boot configuration:
```
ro root=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
apparmor=1 security=apparmor
dolvm root_trim=yes
crypt_root=PARTUUID=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
root_key=/keys/gentoo.key
root_keydev=PARTUUID=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
root_header=/keys/gentoo.hdr
root_headerdev=PARTUUID=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
```

@Whissi Can you please review this PR?

**Comment by reagentoo** [comment]
@Whissi are you going to review?

**Comment by Whissi** [comment]
I am sorry but this will definitely not be considered for next genkernel release (4.2) which is around the corner.
However, I have Nitro key support on my todo list which will require a rewrite of how we handle LUKS. Maybe this rewrite will allow us to add support for detached headers (including support for multiple volumes, bug 694778), too.

**Comment by reagentoo** [comment]
> I am sorry but this will definitely not be considered for next genkernel release (4.2) which is around the corner.
> However, I have Nitro key support on my todo list which will require a rewrite of how we handle LUKS. Maybe this rewrite will allow us to add support for detached headers (including support for multiple volumes, bug 694778), too.

It's awful. Because I use detached headers every day. And I have to spend effort every time to update this patches.

**Pull request merged**
